/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Arlen' at '17-7-20 上午10:24' with Gradle 3.2.1
 *
 * @author Arlen, @date 17-7-20 上午10:24
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
